### ISSUE TITLE
Creating data nodes for xml node sets

### ISSUE THREAD

**Issue by erboose** [blernermhc/RDataTracker#62]
RDataTracker is unable to process the R script hf-dataset-preview.r (which uses the XML library) when function annotations are enabled. When this script is run using "ddg.run", the R interpreter returns the following error message: "Error in as.vector(x, \"character\"): cannot coerce type 'externalptr' to vector of type 'character'\n".  The error appears to be related to the statements "ns <- getNodeSet(eml, xpath)" and "datafile.ids <- get.all.datafile.ids(ns)" in the function "get.datafile.ids()". Note that the node set returned by getNodeSet() is a list.

**Comment by blernermhc** [comment]
The node set is a list where the elements in the list have type externalptr.  externalptr data is data that has been created and is manipulated by C code.  I don't think there is much we can do with these.  We will need to catch the exception and not try to put the value into the DDG.

**Comment by erboose** [comment]
Right. So one option would be to create a data node and set the value to "Not Recorded".  Another option in this case would be to use capture.output (or a similar function) to store what the user sees when the variable holding the node set is evaluated in the console.

**Comment by blernermhc** [comment]
This is fixed in version 1.004.  If a value in a list cannot be converted to a string, it calls capture.output on the print function for the object.
