### ISSUE TITLE
Associate line numbers with nodes

### ISSUE THREAD

**Issue by blernermhc** [blernermhc/RDataTracker#65]
It may be useful to record line numbers within an R script in procedure and data nodes that correspond to the creation of those nodes.  This probably only makes sense in situations where the user is running from a script contained in a file, rather than from the console.

**Comment by sckott** [comment]
+1

**Comment by erboose** [comment]
Each procedure node is now associated with the line number of the corresponding top-level statement in the original script. In the case of multi-line statements (e.g. function definitions), the number is the first line of the statement. Procedure node line numbers and data flow edges may be used to determine where in the script a data value was created and/or used.
