### ISSUE TITLE
Changes to global variables from inside a function

### ISSUE THREAD

**Issue by blernermhc** [blernermhc/RDataTracker#67]
Currently if a function modifies a global variable, that change will not be captured in the DDG unless the user manually annotates it.  For example,

```R
f <- function() {
   a <<- b * 10
}
```
The user could annotate this as:
```R
f <- function() {
   a <<- b * 10
   ddg.function(outs.data=list("a"))
}
```
It would be better to capture this automatically.
See ScopeTest.R for an example.

**Comment by erboose** [comment]
Global variables assigned within a function are now captured automatically with the correct scope.
