### ISSUE TITLE
Incorrect numbering of data nodes

### ISSUE THREAD

**Issue by erboose** [blernermhc/RDataTracker#84]
The DDG for hf-dataset-preview.r contains two data nodes with number 31 (Exception d31 and Data d31) and no data node with number 30.  The data nodes file contains a single entry for 31 (Data 31 eml complex) and no entry for 30.  In DDG Explorer the first error node (31-error.msg) is displayed in the search list when searching for errors, but DDG Explorer is unable to display the node until parts of the DDG are expanded.

**Comment by blernermhc** [comment]
HFDatasetPreview no longer exhibits the problem.  This was probably fixed as a side effect of another fix.
